name: Build DOSBox 64-bit Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build DOSBox 64-bit Release
    runs-on: windows-2022

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: true  # Ensure submodules are checked out

      - name: Install vcpkg
        shell: pwsh
        run: |
          $vcpkgRoot = "C:\vcpkg"
          if (-not (Test-Path -Path $vcpkgRoot)) {
            git clone https://github.com/microsoft/vcpkg.git $vcpkgRoot
            cd $vcpkgRoot
            .\bootstrap-vcpkg.bat -disableMetrics
          }

      - name: Integrate vcpkg
        shell: pwsh
        run: |
          $vcpkgRoot = "C:\vcpkg"
          cd $vcpkgRoot
          .\vcpkg.exe integrate install

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v2
        with:
          vs-prerelease: true
          msbuild-architecture: x64  # Specify the architecture you want to build

      - name: Build DOSBox Solution
        shell: pwsh
        run: |
          $solutionPath = "vs\dosbox.sln"
          MSBuild $solutionPath -t:Rebuild -p:Configuration=Release -p:Platform=x64
          if (-not $?) {
            throw "Build failed for configuration: Release, platform: x64"
          }

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: DOSBox-64bit-Release
          path: vs\x64\Release\*.exe